#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "mainline" ]; then
  echo ""
  while true; do
      read -p "[pre-commit hook] Are you sure you want to commit to mainline? (y/N) " yn
      if [ "$yn" = "" ]; then
          yn='N'
      fi
      case $yn in
          [Yy] ) break;;
          [Nn] ) exit 1;;
          * ) echo "Please answer y or n for yes or no.";;
      esac
  done
fi
